version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasictsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

      
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    depends_on: 
      - elasticsearch
    ports:
      - 3000:3000
   
  web:
    build: ./aylien_app
    command: uvicorn main:app --host 0.0.0.0
    env_file:
      - aylien_app/aylien_env_settings/.env.dev
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    
    volumes:
      - ./aylien_app:/aylien_app
    ports:
      - 8000:8000  
    depends_on: 
      - elasticsearch  


volumes:
  elasictsearch-data:
    driver: local
